language: scala

scala:
    - 2.12.2

jdk:
    - oraclejdk8

script:
  - sbt clean coverage test coverageReport coverageAggregate

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
